apiVersion: v1
kind: Service
metadata:
  name: {{ include "senderservice.fullname" . }}-service
  namespace: {{ .Values.namespace | default .Release.Namespace }} # Added default for safety
  labels:
    app: {{ include "senderservice.name" . }}
spec:
  type: {{ .Values.service.type }}
  selector:
    app: {{ include "senderservice.name" . }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.targetPort }}
      name: http # <--- CRITICAL FIX: Explicitly names the port for the ServiceMonitor
      {{- if eq .Values.service.type "NodePort" }}
      nodePort: {{ .Values.service.nodePort }}
      {{- end }}